Move nGen build to local runner, convert dockerfile to binary/data only

diff --git a/.github/workflows/Example_model_run.yml b/.github/workflows/Example_model_run.yml
--- a/.github/workflows/Example_model_run.yml
+++ b/.github/workflows/Example_model_run.yml
@@ -15,8 +15,29 @@ jobs:
       steps:
       - name: Checkout the code
         uses: actions/checkout@v2
-      - name: PWD
-        run: pwd && git status
+      - name: git submodule
+        run: git submodule update --init --recursive -- test/googletest
+
+      - name: Cache Boost Dependency
+        id: cache-boost-dep
+        uses: actions/cache@v1
+        with:
+          path: boost_1_72_0
+          key: unix-boost-dep
+
+      - name: Get Boost Dependency
+        if: steps.cache-boost-dep.outputs.cache-hit != 'true'
+        run: |
+          curl -L -O https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.bz2
+          tar xjf boost_1_72_0.tar.bz2
+          - name: cmake_init_build
+        run: |
+          export BOOST_ROOT="$(pwd)/boost_1_72_0"
+          [ ! -d "$BOOST_ROOT" ] && echo "Error: no Boost root found at $BOOST_ROOT" && exit 1
+          cmake -B cmake_build -DBMI_C_LIB_ACTIVE:BOOL=OFF -S .
+      - name: Build nGen
+        run: cmake -B /ngen -S .
+        run: cmake --build /ngen --target ngen
       - name: Build the NGEN image
         run: docker build . --file ./docker/CENTOS_NGEN_RUN.dockerfile --tag localbuild/ngen:latest      
       - name: Run the NGEN model on example data
